### ISSUE TITLE
Not Running In My PC, Selenium and Driver both are already installed, BTW i am also making but bit easy one

### ISSUE THREAD

**Issue by ayushkumar29** [TheFenrisLycaon/BlackBoard-Auto#2]

**Comment by TheFenrisLycaon** [comment]
Give me your device specs

**Comment by ayushkumar29** [comment]
I7 10gen, 8gm ram 512gb ssd

**Comment by ayushkumar29** [comment]
the problem is that , it not asking for my time table

**Comment by TheFenrisLycaon** [comment]
Show me your screenshot.
Check if there is something is the data folder. Delete folder and try again.
